services:
  - type: web
    name: ffj-tree-aadhar-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        value: ffj@jecrc2025
