export const initialTrees = [
  {
    treeId: 'FFJ-TREE-0001',
    commonName: 'Mango',
    scientificName: 'Mangifera indica',
    localName: 'आम (Aam)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782473998/FFJ_dev/dqmtfhbt6sng7dnmsisv.jpg',
      'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop',
    ],
    description: 'Known affectionately as the "King of Fruits," the Mango is a deeply cherished part of Indian culture, where its leaves are strung across doorways during festivals to bring good luck. Planted in the prime sunlit area of Central Lawn at JECRC.',
    healthBenefits: 'Incredibly rich in Vitamins A and C, which naturally boost immunity and keep skin glowing. Supports digestive enzymes and eye health.',
    culturalSignificance: 'Sacred in Hindu traditions. Mango leaves (Toran) signify fertility, prosperity, and divine blessings during housewarmings and Diwali celebrations.',
    plantedDate: new Date('2022-07-15'),
    plantedBy: 'Dr. Amit Sharma & JECRC Environment Cell',
    location: {
      zone: 'Block A - Central Lawn',
      latitude: 26.78210,
      longitude: 75.82245,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-10'),
    height: 4.8,
    girth: 48,
    caretakerName: 'Ramesh Ji (Senior Horticulturist)',
  },
  {
    treeId: 'FFJ-TREE-0002',
    commonName: 'Curry Leaves',
    scientificName: 'Murraya koenigii',
    localName: 'कढ़ी पत्ता (Kadi Patta)',
    category: 'Medicinal',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782474098/FFJ_dev/fhsi7g9egvnzz93q0aig.jpg',
    ],
    description: 'Essential for that comforting traditional tadka, this aromatic shrub thrives in our campus medicinal grove. Releases rich aromatic oils when leaves are lightly bruised.',
    healthBenefits: 'Packed with iron, calcium, and digestion-friendly compounds. Traditionally infused into coconut oil for healthy hair growth and blood glucose moderation.',
    culturalSignificance: 'A cornerstone of South Asian domestic kitchens and Ayurvedic daily rasayana regimens.',
    plantedDate: new Date('2023-03-22'),
    plantedBy: 'Batch of 2023 - Department of Biotechnology',
    location: {
      zone: 'Ayurvedic Herbal Garden',
      latitude: 26.78235,
      longitude: 75.82270,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-14'),
    height: 2.1,
    girth: 18,
    caretakerName: 'Sita Devi (Campus Herbalist)',
  },
  {
    treeId: 'FFJ-TREE-0003',
    commonName: 'Chiku (Sapodilla)',
    scientificName: 'Manilkara zapota',
    localName: 'चीकू (Chiku)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782474315/FFJ_dev/gc4em19pnshkuo8zem6w.jpg',
    ],
    description: 'A resilient evergreen tree famous for producing sweet, malty, brown granular fruits that thrive wonderfully in Rajasthan’s sunny climate.',
    healthBenefits: 'Fantastic natural energy booster loaded with natural fructose and dietary fiber. Rich in tannins that act as natural antioxidants.',
    culturalSignificance: 'A classic Indian kitchen garden favorite, cherished in family smoothies, halwas, and seasonal college harvest festivals.',
    plantedDate: new Date('2022-09-05'),
    plantedBy: 'Teachers Day Plantation Drive 2022',
    location: {
      zone: 'Block B - Botanical Quad',
      latitude: 26.78185,
      longitude: 75.82260,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-08'),
    height: 3.6,
    girth: 34,
    caretakerName: 'Ramesh Ji',
  },
  {
    treeId: 'FFJ-TREE-0004',
    commonName: 'Bael (Wood Apple)',
    scientificName: 'Aegle marmelos',
    localName: 'बेल (Bilva Patra)',
    category: 'Medicinal',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782474519/FFJ_dev/oryp9el77yk6dhdnw4nj.jpg',
    ],
    description: 'Bael is one of Ayurveda’s greatest gifts for digestive wellness. Its aromatic trifoliate leaves and tough-shelled cooling fruits withstand harsh Rajasthan summers with exceptional drought resistance.',
    healthBenefits: 'Cools the digestive tract, cures chronic stomach upsets, and balances gut flora. The pulp is made into gut-healing summer sherbets.',
    culturalSignificance: 'Sacred to Lord Shiva; its trifoliate leaves symbolize the Tridevas and Trishul and are offered in campus temple ceremonies.',
    plantedDate: new Date('2021-08-15'),
    plantedBy: 'JECRC Foundation Heritage Council',
    location: {
      zone: 'Ayurvedic Herbal Garden',
      latitude: 26.78240,
      longitude: 75.82285,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-12'),
    height: 5.4,
    girth: 52,
    caretakerName: 'Green Campus Volunteer Wing',
  },
  {
    treeId: 'FFJ-TREE-0005',
    commonName: 'Amla (Indian Gooseberry)',
    scientificName: 'Phyllanthus emblica',
    localName: 'आंवला (Amla)',
    category: 'Medicinal',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782474779/FFJ_dev/yawv5ixzh16yamz1kr7q.jpg',
    ],
    description: 'A cornerstone of traditional Indian wellness and the primary active ingredient in the revered immunity tonic Chyawanprash. Known as the eternal youth tree.',
    healthBenefits: 'Supreme superfood containing nearly twenty times more Vitamin C than citrus fruits. Strengthens hair roots, improves skin luster, and purifies toxins.',
    culturalSignificance: 'Celebrated on Amla Navami; families historically picnic under its purifying shade to absorb its therapeutic prana.',
    plantedDate: new Date('2023-01-26'),
    plantedBy: 'Republic Day Green Mission 2023',
    location: {
      zone: 'Block B - Botanical Quad',
      latitude: 26.78170,
      longitude: 75.82230,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-11'),
    height: 3.1,
    girth: 27,
    caretakerName: 'Sita Devi',
  },
  {
    treeId: 'FFJ-TREE-0006',
    commonName: 'Orange (Santra)',
    scientificName: 'Citrus sinensis',
    localName: 'संतरा (Santra)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782474981/FFJ_dev/tjg18gsngecdirhiczfy.jpg',
    ],
    description: 'Evoking crisp winter mornings in Rajasthan, our Santra trees burst with fragrant white blossoms in spring and radiant orange orbs in winter.',
    healthBenefits: 'Loaded with bioavailable Vitamin C, dietary fiber, and hesperidin for cardiac and capillary health.',
    culturalSignificance: 'Symbolizes vitality, cheerfulness, and generosity across festival harvest celebrations.',
    plantedDate: new Date('2023-07-20'),
    plantedBy: 'Rotaract Club of JECRC',
    location: {
      zone: 'Academic Block 1 Perimeter',
      latitude: 26.78200,
      longitude: 75.82310,
    },
    healthStatus: 'Needs Attention',
    lastCheckupDate: new Date('2025-01-05'),
    height: 2.7,
    girth: 22,
    caretakerName: 'Ramesh Ji',
  },
  {
    treeId: 'FFJ-TREE-0007',
    commonName: 'Lemon (Nimbu)',
    scientificName: 'Citrus limon',
    localName: 'नींबू (Nimbu)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782475053/FFJ_dev/bjbiskdfbjyzqtur9g1b.jpg',
    ],
    description: 'From warding off negative energies to delivering India’s favorite summer remedy Shikanji, this thorny citrus tree is an indispensable campus presence.',
    healthBenefits: 'Purifies digestion, hydrates with alkaline electrolytes, and stimulates lymphatic detox.',
    culturalSignificance: 'A household talisman of protection against the evil eye (nazar) and symbol of purity.',
    plantedDate: new Date('2022-11-14'),
    plantedBy: 'Children\'s Day Eco Drive',
    location: {
      zone: 'Hostel Circle Green Corridor',
      latitude: 26.78160,
      longitude: 75.82290,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-09'),
    height: 2.4,
    girth: 19,
    caretakerName: 'Hostel Green Council',
  },
  {
    treeId: 'FFJ-TREE-0008',
    commonName: 'Guava (Amrood)',
    scientificName: 'Psidium guajava',
    localName: 'अमरूद (Amrood)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782475282/FFJ_dev/bq5ibjfeyz0mxt68kucr.jpg',
    ],
    description: 'Highly resilient fruit tree thriving with crisp pink and white flesh guavas. The young tender leaves are routinely harvested by students for soothing throat remedies.',
    healthBenefits: 'One of the highest dietary fiber contents of any fruit, lowers blood sugar spikes, and is extremely rich in potassium and lycopene.',
    culturalSignificance: 'Iconic winter comfort fruit enjoyed across North Indian colleges with chaat masala and black salt.',
    plantedDate: new Date('2022-08-01'),
    plantedBy: 'Prof. S.K. Vyas (Dean Academics)',
    location: {
      zone: 'Sports Complex Tree Line',
      latitude: 26.78250,
      longitude: 75.82215,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-13'),
    height: 3.9,
    girth: 36,
    caretakerName: 'Sports Complex Ground Staff',
  },
  {
    treeId: 'FFJ-TREE-0009',
    commonName: 'Banana Plant',
    scientificName: 'Musa acuminata',
    localName: 'केला (Kela)',
    category: 'Fruit',
    photos: [
      'https://res.cloudinary.com/dcn93ic66/image/upload/v1782475372/FFJ_dev/jlybfivphcxt9qep19ly.jpg',
    ],
    description: 'Fast-growing giant herbaceous plant with majestic canopy leaves. Every single component—fruit, flower heart, stem, and biodegradable leaf plate—is utilized.',
    healthBenefits: 'Potent source of instant natural energy, potassium, Vitamin B6, and prebiotic resistant starch.',
    culturalSignificance: 'Sacred embodiment of Lord Vishnu and Goddess Lakshmi; used at wedding entry arches to bless unions with endless bounty.',
    plantedDate: new Date('2023-08-15'),
    plantedBy: 'Independence Day Eco-Pledge 2023',
    location: {
      zone: 'Hostel Circle Green Corridor',
      latitude: 26.78150,
      longitude: 75.82320,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-10'),
    height: 3.2,
    girth: 29,
    caretakerName: 'Ramesh Ji',
  },
  {
    treeId: 'FFJ-TREE-0010',
    commonName: 'Neem',
    scientificName: 'Azadirachta indica',
    localName: 'नीम (Neem)',
    category: 'Medicinal',
    photos: [
      'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800&auto=format&fit=crop',
    ],
    description: 'The ancient grand guardian of Indian air. Known as the "free tree of India" and the campus natural air purifier, providing dense cooling shade all year long.',
    healthBenefits: 'Supreme antibacterial, antiviral, and blood-purifying properties. Twigs (datun) traditionally maintain pristine oral hygiene.',
    culturalSignificance: 'Considered a manifestation of Goddess Shitala. Revered as the natural village pharmacy.',
    plantedDate: new Date('2020-06-05'),
    plantedBy: 'World Environment Day Founders Drive',
    location: {
      zone: 'Block A - Central Lawn',
      latitude: 26.78225,
      longitude: 75.82230,
    },
    healthStatus: 'Healthy',
    lastCheckupDate: new Date('2025-01-12'),
    height: 7.2,
    girth: 84,
    caretakerName: 'Ramesh Ji & Green Volunteers',
  },
];
